# Generated by Django 5.1.4 on 2024-12-23 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iPhone', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iphone',
            name='description',
        ),
    ]
