# Generated by Django 5.1.4 on 2024-12-23 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iPhone', '0002_remove_iphone_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='iphone',
            name='color',
            field=models.CharField(default='Nero', max_length=50),
        ),
    ]
