# Generated by Django 5.1.4 on 2024-12-23 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iPhone', '0003_iphone_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iphone',
            name='color',
            field=models.CharField(choices=[('nero', 'Nero'), ('bianco', 'Bianco'), ('rosso', 'Rosso'), ('giallo', 'Giallo'), ('verde', 'Verde'), ('blu', 'Blu'), ('viola', 'Viola')], default='Nero', max_length=50),
        ),
    ]
