# Generated by Django 5.1.4 on 2024-12-23 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iPhone', '0004_alter_iphone_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='iphone',
            name='space',
            field=models.IntegerField(choices=[(64, 64), (128, 128), (256, 256), (512, 512), (1024, 1024)], default=64),
        ),
        migrations.AlterField(
            model_name='iphone',
            name='color',
            field=models.CharField(choices=[('Nero', 'Nero'), ('Bianco', 'Bianco'), ('Oro', 'Oro'), ('Blu', 'Blu'), ('Verde', 'Verde'), ('Rosso', 'Rosso'), ('Giallo', 'Giallo')], default='Nero', max_length=50),
        ),
    ]
