# Generated by Django 5.1.4 on 2024-12-23 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iPhone', '0005_iphone_space_alter_iphone_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='iphone',
            name='display',
            field=models.FloatField(choices=[(6.1, 6.1), (6.7, 6.7)], default=6.1),
        ),
    ]
